services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pizzacms
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: user
      DATABASE_PASSWORD: userpassword
      DATABASE_NAME: pizzacms
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  frontend:
    build:
      context: ./cms-front
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - "3001:3000"
    volumes:
      - ./cms-front:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

volumes:
  mysql_data:
